# Week 4 Day 1 Lab

Generally useful functions:
```python
df.head()
df.tail()
df.info()
df.describe()
df.shape
df.columns
df.isnull().sum()
df.duplicated().sum()
df.corr(numeric_only=True)
df.value_counts()
```

Useful plotting functions:

```python
plt.hist()
plt.scatter()
plt.bar()
plt.boxplot()
df.plot()
```

where `df` is a `pandas.DataFrame` object and `plt` is the `matplotlib.pyplot` library


### Problem 1: Data Selection

Choose **one** of the following datasets on GitHub:
- Iris Dataset
- Titanic Dataset

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv(r"C:\Users\bryce\GitHub\Math-300---Mathematical-Computing\Datasets\titanic.csv")

### Problem 2: Loading the Data
1. Load the dataset into a Pandas DataFrame.
2. Display the first five rows.
3. Display the last five rows.

In [13]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [14]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

### Problem 3: Inspect Data
1. How many rows are in the dataset?
2. How many columns are in the dataset?
3. What are the column names?
4. What data type is each column?
5. Are there any missing values?
6. Are there any duplicate rows?

In [ ]:
#1  891
#2  10
#3  PassengerId	Survived	Pclass	Name	Sex	Age	SibSp	Parch	Ticket	Fare	Cabin	Embarked
#4  int, int, int, string, string, float, int, int, int, float, string, string
#5  Yes
#6
df.value_counts()
  # I Believe there is

### Problem 4: Summary Statistics
For each numerical column, compute the following:
- Mean
- Median
- Mode
- Minimum
- Maximum
- Standard deviation


1. Which variable has the greatest variation?
2. Which variable has the smallest variation?

In [25]:
number_columns = df.select_dtypes(include=['number'])
print(number_columns.mean())
print()
print(number_columns.median())
print()
print(number_columns.mode().iloc[0])
print(number_columns.min())
print()
print(number_columns.max())
print()
print(number_columns.std())
print()

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

PassengerId    446.0000
Survived         0.0000
Pclass           3.0000
Age             28.0000
SibSp            0.0000
Parch            0.0000
Fare            14.4542
dtype: float64

PassengerId     1.00
Survived        0.00
Pclass          3.00
Age            24.00
SibSp           0.00
Parch           0.00
Fare            8.05
Name: 0, dtype: float64
PassengerId    1.00
Survived       0.00
Pclass         1.00
Age            0.42
SibSp          0.00
Parch          0.00
Fare           0.00
dtype: float64

PassengerId    891.0000
Survived         1.0000
Pclass           3.0000
Age             80.0000
SibSp            8.0000
Parch            6.0000
Fare           512.3292
dtype: float64

PassengerId    257.353842
Survived         0.486592
Pclass           0.836071
Age             14.526497
SibSp            1.102743
Parch            0.806057
Fare            49.693429
dtype: float64

In [ ]:
#1
    # If not counting ID # then Fare would becuase of it large Max and small Min
#2
    # Survided ranges from 0 to 1

### Problem 5: Visualization
1. Choose a numerical column from your dataset and:
    - Plot the corresponding histogram. 
        - What does the distribution look like?
        - Is it symmetric or skewed?
    - Plot the corresponding box plot.
        - Are there any outliers?
        - Explain what you observe.
2. Choose one categorical column from your dataset and:
    - Plot the corresponding bar chart.
        - Which category occurs most frequently?
        - Which occurs least frequently?